/**
 * Lambda Function: savePlannedTasks
 * 
 * Saves the replanned tasks generated by Bedrock agent to your database.
 * Deletes old pending tasks and inserts new ones.
 */

exports.handler = async (event) => {
    console.log('savePlannedTasks invoked with:', JSON.stringify(event));
    
    try {
        const { userEmail, tasks, subjects } = event.parameters || event;
        
        if (!userEmail || !tasks) {
            return {
                statusCode: 400,
                body: {
                    error: 'userEmail and tasks are required'
                }
            };
        }
        
        // Parse tasks if it's a string
        const parsedTasks = typeof tasks === 'string' ? JSON.parse(tasks) : tasks;
        
        if (!Array.isArray(parsedTasks) || parsedTasks.length === 0) {
            return {
                statusCode: 400,
                body: {
                    error: 'tasks must be a non-empty array'
                }
            };
        }
        
        // TODO: Replace with actual database operations
        
        // Step 1: Delete old pending tasks for the subjects being replanned
        const subjectsToUpdate = subjects 
            ? (typeof subjects === 'string' ? JSON.parse(subjects) : subjects)
            : [...new Set(parsedTasks.map(t => t.subject))];
        
        console.log(`Deleting pending tasks for subjects: ${subjectsToUpdate.join(', ')}`);
        
        // await db.deletePendingTasks(userEmail, subjectsToUpdate);
        
        // Step 2: Save new tasks
        console.log(`Saving ${parsedTasks.length} new tasks`);
        
        const tasksToSave = parsedTasks.map(task => ({
            ...task,
            userEmail: userEmail,
            id: task.id || `task_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
            createdAt: new Date().toISOString()
        }));
        
        // await db.saveTasks(userEmail, tasksToSave);
        
        // Step 3: Update lastReplanned timestamp for affected goals
        const todayStr = new Date().toISOString().split('T')[0];
        
        // await db.updateOnboardingLastReplanned(userEmail, subjectsToUpdate, todayStr);
        
        console.log(`Successfully saved ${tasksToSave.length} tasks`);
        
        return {
            statusCode: 200,
            body: {
                message: 'Tasks saved successfully',
                taskCount: tasksToSave.length,
                subjects: subjectsToUpdate,
                savedTasks: tasksToSave
            }
        };
        
    } catch (error) {
        console.error('Error in savePlannedTasks:', error);
        return {
            statusCode: 500,
            body: {
                error: 'Failed to save tasks',
                message: error.message
            }
        };
    }
};
