
import React from 'react';
import { StudyTask, OnboardingData } from '../types';

interface UserProfileProps {
    tasks: StudyTask[];
    onboardingData: OnboardingData | null;
    onBack: () => void;
    onLogout: () => void;
    onStartNewPlan: () => void;
}

const UserProfile: React.FC<UserProfileProps> = ({ tasks, onboardingData, onBack, onLogout, onStartNewPlan }) => {
    const completedTasks = tasks.filter(t => t.status === 'completed');
    const totalTasks = tasks.length;
    const completionRate = totalTasks > 0 ? Math.round((completedTasks.length / totalTasks) * 100) : 0;

    const userName = onboardingData ? "Learner" : "Student"; // Replace with real name if available

    return (
        <div className="max-w-4xl mx-auto py-12 pt-32 px-6 animate-fade-in min-h-screen">
            <div className="flex items-center gap-6 mb-12">
                <button onClick={onBack} className="p-3 hover:bg-slate-100 rounded-2xl text-slate-500 transition-all active:scale-95 border border-slate-100">
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path d="M15 19l-7-7 7-7" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                </button>
                <div>
                    <h1 className="text-4xl font-bold text-slate-900 tracking-tight">My Profile</h1>
                    <p className="text-slate-500 font-light mt-1">Your learning peak and achievements.</p>
                </div>
            </div>

            <div className="grid md:grid-cols-3 gap-6 mb-12">
                <div className="bg-white border border-slate-100 p-8 rounded-[32px] shadow-sm flex flex-col items-center text-center">
                    <div className="w-16 h-16 bg-indigo-50 rounded-full flex items-center justify-center mb-4 border border-indigo-100/50">
                        <span className="text-2xl font-bold text-indigo-600">{totalTasks}</span>
                    </div>
                    <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Total Tasks</h3>
                    <p className="text-sm text-slate-500 mt-1">Generated by AI</p>
                </div>

                <div className="bg-emerald-50/50 border border-emerald-100 p-8 rounded-[32px] shadow-sm flex flex-col items-center text-center">
                    <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mb-4 border border-emerald-200/50">
                        <span className="text-2xl font-bold text-emerald-600">{completedTasks.length}</span>
                    </div>
                    <h3 className="text-xs font-bold text-emerald-600 uppercase tracking-widest text-opacity-70">Completed</h3>
                    <p className="text-sm text-emerald-600/70 mt-1">Milestones reached</p>
                </div>

                <div className="bg-slate-900 border border-slate-800 p-8 rounded-[32px] shadow-xl flex flex-col items-center text-center">
                    <div className="w-16 h-16 bg-white/10 rounded-full flex items-center justify-center mb-4 border border-white/20">
                        <span className="text-2xl font-bold text-white">{completionRate}%</span>
                    </div>
                    <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Mastery</h3>
                    <p className="text-sm text-slate-400/70 mt-1">Course progress</p>
                </div>
            </div>

            <section>
                <div className="flex items-center justify-between mb-8 px-2">
                    <h2 className="text-xl font-bold text-slate-800 tracking-tight">Completed Sessions</h2>
                    <span className="bg-emerald-50 text-emerald-600 text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-widest border border-emerald-100">
                        {completedTasks.length} Done
                    </span>
                </div>

                <div className="space-y-4">
                    {completedTasks.length > 0 ? (
                        completedTasks.map((task) => (
                            <div key={task.id} className="bg-white border border-slate-100 p-6 rounded-2xl shadow-sm hover:shadow-md transition-all flex justify-between items-center group">
                                <div className="flex gap-6 items-center">
                                    <div className="bg-emerald-50 p-3 rounded-xl border border-emerald-100 group-hover:scale-110 transition-transform">
                                        <svg className="w-5 h-5 text-emerald-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M5 13l4 4L19 7" />
                                        </svg>
                                    </div>
                                    <div>
                                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-0.5">{task.subject}</span>
                                        <h3 className="font-bold text-primary">{task.topic}</h3>
                                        <p className="text-sm text-slate-500 font-light">{task.subtopic}</p>
                                    </div>
                                </div>
                                <div className="text-right">
                                    <span className="text-[10px] font-bold text-slate-400 block uppercase tracking-widest">Date</span>
                                    <span className="text-xs font-bold text-primary">{task.date}</span>
                                </div>
                            </div>
                        ))
                    ) : (
                        <div className="py-24 text-center border-2 border-dashed border-slate-100 rounded-[40px] bg-slate-50/50">
                            <span className="text-5xl mb-6 block opacity-20">🏆</span>
                            <p className="text-slate-500 font-medium">Your trophy shelf is waiting.</p>
                            <p className="text-slate-400 text-xs mt-2 px-6 max-w-xs mx-auto">Tasks you complete will be automatically logged here as achievements.</p>
                        </div>
                    )}
                </div>
            </section>

            <div className="mt-12 flex justify-center">
                <button
                    onClick={onStartNewPlan}
                    className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-3.5 rounded-2xl text-sm font-bold transition-all shadow-lg active:scale-95 flex items-center gap-3"
                >
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                    Plan for Another Exam
                </button>
            </div>

            <div className="mt-20 pt-12 border-t border-slate-100 flex justify-center">
                <button
                    onClick={onLogout}
                    className="bg-red-50 text-red-500 px-8 py-3 rounded-2xl text-sm font-bold border border-red-100 hover:bg-red-100 transition-all flex items-center gap-3 shadow-signout"
                >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                    </svg>
                    Sign Out of Adapta
                </button>
            </div>
        </div>
    );
};

export default UserProfile;
